version: 2.1

description: "Common CircleCI tasks for Hugo."

executors:
  image:
    parameters:
      version:
        description: "The CI Builds Hugo Docker image."
        type: string
        default: "latest"
    docker:
      - image: cibuilds/hugo:<< parameters.version >>

commands:
  install:
    description: "Install Hugo into your image."
    parameters:
      version:
        description: "The Hugo version."
        type: string
      extended:
        description: "Install the Hugo extended binary?"
        type: boolean
        default: true
    steps:
      - run:
          name: "Install Hugo"
          command: |
            if [ -f /etc/alpine-release ]; then
              apk add build-base curl libcurl libc6-compat libxml2-dev libxslt-dev
            fi

            if [ << parameters.extended >> = true ]; then
              HUGO_EXTENDED="_extended"
            else
              HUGO_EXTENDED=""
            fi

            HUGO_URL=https://github.com/gohugoio/hugo/releases/download/v<< parameters.version >>/hugo${HUGO_EXTENDED}_<< parameters.version >>_Linux-64bit.tar.gz

            curl -sSL "$HUGO_URL" | tar -xz -C /usr/local/bin hugo
